version: '3.7'

services:
  frontend:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./persist/html/:/var/www/html/
      - ./persist/ssl/:/etc/apache2/ssl/
    image: ttrss:frontend
    depends_on:
      - mysql
    links:
      - "mysql:db"
  mysql:
    image: ttrss:mysql
    hostname: mysql
    volumes:
      - type: bind
        source: ./persist/mysql
        target: /var/lib/mysql/
    env_file:
      - config/mysql-variables.env
